Regiter and login
PDaI-Group-12/backend pull request #12
Opened 2024-11-06 23:02 UTC by KeranenEelis10

Register and login backend. Could probably be still improved but merging so others can start their work. Tested successfully in postman

2024-11-07 12:11 UTC, vima20 approved these changes

2024-11-08 08:13 UTC, syorito-hatsuki requested changes

2024-11-08 08:13 UTC, syorito-hatsuki commented on controllers/authController.ts
Use unspecified error message "Username or password incorrect" to avoid Brutforce

2024-11-11 09:20 UTC, KeranenEelis10 commented
Changes made

2024-11-11 09:23 UTC, syorito-hatsuki approved these changes

2024-11-11 09:23 UTC, merged